export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_STORY = 'SAVE_STORY';
export const SAVE_BADTOKENS = 'SAVE_BADTOKENS';